//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SineWave.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_APPLICATIONSTEP2_DIALOG     102
#define IDS_SHOW_DEGREES                102
#define IDS_SAMPLES                     103
#define IDS_SELECT_BIT                  104
#define IDS_APP_CAPTION                 105
#define IDR_MAINFRAME                   128
#define IDC_GRAPH                       1000
#define IDC_INVALIDATE                  1001
#define IDC_SHOWSINE                    1002
#define IDC_SHOWSTEP                    1003
#define IDC_STEPS                       1004
#define IDC_SPINSTEPS                   1005
#define IDC_SHOWDEBUG                   1006
#define IDC_THETA                       1007
#define IDC_SPINTHETA                   1008
#define IDC_SAMPLE                      1009
#define IDC_SAMPLES                     1010
#define IDC_SHOW_SAMPLES                1011
#define IDC_SHOWAXIS                    1012
#define IDC_WAVES                       1013
#define IDC_SPINWAVES                   1014
#define IDC_FRAME                       1015
#define IDC_RECTIFY_NONE                1016
#define IDC_RECTIFY_HALF                1017
#define IDC_RECTIFY_FULL                1018
#define IDC_PHASE                       1019
#define IDC_SPINPHASE                   1020
#define IDC_SHOW_RMS                    1021
#define IDC_SHOWCLASSD                  1022
#define IDC_ZEROPHASE                   1023
#define IDC_DEBUGXY                     1024
#define IDC_ZERO_CENTER                 1025
#define IDC_ZERO_BOTTOM                 1026
#define IDC_SHOWBASE                    1027
#define IDC_SHOWSUM                     1028
#define IDC_SHOWDIFF                    1029
#define IDC_NINETYPHASE                 1030
#define IDC_ONEEIGHTYPHASE              1031
#define IDC_TWOSEVENTYPHASE             1032
#define IDC_ADC_8                       1033
#define IDC_ADC_10                      1034
#define IDC_ADC_11                      1035
#define IDC_ADC_12                      1036
#define IDC_ADC_16                      1037
#define IDC_ADC                         1038
#define IDC_ACD_CAPTION                 1039
#define IDC_CAPACITOR                   1040
#define IDC_LOAD                        1041
#define IDC_50HZ                        1042
#define IDC_60HZ                        1043
#define IDC_CAPACITANCE                 1044
#define IDC_RESISTANCE                  1045
#define IDC_SHOWFILTERED                1046
#define IDC_HZ_CAPTION                  1047
#define IDC_CAPACITANCE_CAPTION         1048
#define IDC_RESISTANCE_CAPTION          1049
#define IDC_3V3                         1050
#define IDC_5V0                         1051
#define IDC_OTHERV                      1052
#define IDC_OTHER_OUTPUT_V              1052
#define IDC_CURRENT_CAPTION             1053
#define IDC_RESET_ALL                   1054
#define IDC_DEBUG_CAPTION               1055
#define IDC_CIRCUIT                     1056
#define IDC_SHOWREGULATED               1057
#define IDC_SHOWREGULATIONFAILURES      1058
#define IDC_SHOWREGULATIONFAILURE       1058
#define IDC_DROPOUT                     1059
#define IDC_SPIN_DROPOUT                1060
#define IDC_DROPOUT_CAPTION2            1061
#define IDC_DROPOUT_CAPTION1            1062
#define IDC_RECTIFICATION_CAPTION       1063
#define IDC_OTHER_OUTPUT__VALUE         1064
#define IDC_CURRENT                     1065
#define IDC_SPIN_OTHER_OUTPUT_VALUE     1066
#define IDC_6V3                         1067
#define IDC_12V6                        1068
#define IDC_OTHER_INPUT_V               1069
#define IDC_OTHER_INPUT_VALUE           1070
#define IDC_SPIN_OTHER_INPUT__VALUE     1071
#define IDC_INPUT_VOLTAGE_CAPTION       1072
#define IDC_SHOWVALUES                  1073
#define IDC_ZERO_CAPTION                1074
#define IDC_DROPOUT_2V                  1075
#define IDC_DROPOUT_700MV               1076
#define IDC_DROPOUT_200MV               1077
#define IDC_DROPOUT_350MV               1078
#define IDC_AREF_1V0                    1079
#define IDC_AREF_1V1                    1080
#define IDC_AREF_3V3                    1081
#define IDC_AREF_5V0                    1082
#define IDC_AREF_OTHER                  1083
#define IDC_OTHER_AREF_VALUE            1084
#define IDC_SPIN_OTHER_AREF__VALUE      1085
#define IDC_AREF_VALUE_CAPTION2         1086
#define IDC_AREF_VALUE_CAPTION1         1087
#define IDC_POWER_FACTOR                1088
#define IDC_ENABLE_SCHMITT              1089
#define IDC_ON_CAPTION                  1090
#define IDC_ON                          1091
#define IDC_SPIN_ON                     1092
#define IDC_OFF_CAPTION                 1093
#define IDC_OFF                         1094
#define IDC_SPIN_ON2                    1095
#define IDC_SPIN_OFF                    1095
#define IDC_SHOWPWM                     1096
#define IDC_PWM_WIDTH                   1097
#define IDC_SPIN_PWM_WIDTH              1098
#define IDC_PWM_CAPTION                 1099
#define IDC_INVERT_SCHMITT              1100
#define IDC_INVERT_PWM                  1101
#define IDC_VIMAX_CAPTION               1102
#define IDC_VIMAX                       1103
#define IDC_SPIN_VIMAX                  1104
#define IDC_VI_SAFE                     1105
#define IDC_CLIP_FULL                   1106
#define IDC_CLIP_CLIENT                 1107
#define IDC_CLIP_WAVEFORM               1108
#define IDC_CLIP_CAPTION                1109
#define IDC_CLIP_CIRCUIT                1110
#define IDC_INVALIDATE_CIRCUIT          1111
#define IDC_SINE_DASHED                 1112
#define IDC_ADC_PERCENT                 1113
#define IDC_VF                          1114
#define IDC_SPIN_VF                     1115
#define IDC_VF_CAPTION2                 1116
#define IDC_VF_BOX                      1117
#define IDC_VF_200MV                    1118
#define IDC_VF_300MV                    1119
#define IDC_VF_700MV                    1120
#define IDC_ADC_DEC                     1121
#define IDC_ADC_HEX                     1122
#define IDC_ADC_VOLTS                   1123
#define IDC_ADC_CAPTION2                1124
#define IDC_SHOWMARKS                   1124
#define IDC_SHOW_CAPTION                1125
#define IDC_CLIP_WAVEDELAY              1126
#define IDC_PROGRESS1                   1128
#define IDC_SPINNER                     1128

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1129
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
